name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types:
      - on-demand-build

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          key: v1-${{ hashFiles('package-lock.json') }}-${{ hashFiles('elm.json') }}
          restore-keys: |
            v1-${{ hashFiles('package-lock.json') }}-
            v1-
          path: |
            node_modules
            elm-stuff
            .elm-pages
            ~/.elm
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          LINK_PREVIEW_API_KEY: ${{ secrets.LINK_PREVIEW_API_KEY }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/deploy-pages@v1
