name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types:
      - on-demand-build
  schedule:
    - cron: "51 4,16 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: gh-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ contains(github.event.head_commit.message, '[self-hosted]') && 'self-hosted' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master # Explicitly checkout master, since the ref may be updated within the caller workflows
          submodules: recursive
      - uses: actions/cache@v3
        with:
          key: v4-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('elm.json') }}
          restore-keys: |
            v4-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            v4-${{ runner.arch }}-${{ runner.os }}-
          path: |
            node_modules/
            elm-stuff/
            .elm-pages/
            ~/.elm
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
        timeout-minutes: 30
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          BOOKS_JSON_URL: ${{ secrets.BOOKS_JSON_URL }}
          LIBRARY_KEY_SEED_HASH: ${{ secrets.LIBRARY_KEY_SEED_HASH }}
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
  deploy-cloudflare:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: github-pages # default of actions/upload-pages-artifact
          path: .
      - name: untar gzipped artifact.tar into ./dist
        run: tar -xzf ./artifact.tar -C ./dist
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ymtszw-github-io
          directory: ./dist
          # git連携していないPagesプロジェクトのデフォルトは、branchをmainと名付けると本番環境になる
          branch: main
